### PR TITLE
Improves the way summary is being rendered by markdown

### PR DESCRIPTION
**Pull request by ixti**
Resolves issue #18
Improves pull request #88

### CODE REVIEW

**Comment by jbrains** [comment]
This looks good, although I wonder about making this fix specific to link references. It seems safer to process the entire article with Markdown, then extract the summary, so that future changes that create this kind of problem don't lead to future code changes.

**Comment by ixti** [comment]
Thanks for your comment.

I don't see problems to make fix for links references specific issue of summary if it is related to this only :)) Until we have tested features - we can change code and guarantee that it will work as expected. The problem with parsing whole text with Markdown is that after you have received rendered HTML it's really hard to extract summary from it.

Also summary can be either separated by `delimiter` or on max chars based. So I believe that trying to extract summary after article was rendered by Markdown is really hard task that needs even more deep testing because of it's complexity (you need to guarantee that final HTML will be valid and all tags would be closed).

**Comment by seanlin** [comment]
Seems like both of them are not looking at the pull request or just simply abandoned the project?

**Comment by ixti** [comment]
@seanlin, I talked to @cloudhead not far ago, so I don't think he abandoned his child :)) I believe he simply have no time for now to spend on toto :)) Anyway I have my own branch where I have all desired pull requests (mine and some of the others) merged in ;))

@seanlin, if you have some time it would be nice to have your ideas about #25 because I have prepared basic version of categories support, and would like to have some comments - probably I have missed something.

**Comment by seanlin** [comment]
@ixti adding features is cool but I guess toto is supposed to be a minimalist app right from the start, my intention is to provide as many hooks as possible to other web services (or API) so that if a user wants more, he can extend it the way he like

**Comment by ixti** [comment]
@seanlin, in fact I didn't added lots of extra features. I have only added support for tags and categories (as I need them for myself - I love to store things on absolute order) :)) Other pull requests are fixes and improvements :))

**Comment by seanlin** [comment]
@ixti Yup and your fork is something I have been using for tags :) , I just wish you can contribute more improvements. I just changed the way comment works in my fork too for people who wants to use other commenting system and will do pull request once I have done the tests.

**Comment by ixti** [comment]
@seanlin, Yup saw your fork. And glad that you found tags useful. Wanted to recommend replace it a little bit :)) You can provide any config options right in the dorothy, so for example you can put following into your `config.ru`

``` ruby
set :livefyre, "whatever i want"
```

And then replace discus portion under `templates/article` to something like this:

``` html
<% unless @config[:livefyre].nil? or !@config[:livefyre]? %>
  <!-- your portion of livefyre here -->
<% end %>
```

**Pull request closed without merging**
