### PR TITLE
Fixed: index template rendered summary incorrectly if it had a reference-style link

### PR DESCRIPTION
**Pull request by jbrains**
I was using reference-style links (instead of inline links) in an article, and since the referring text was in the summary, but the link definition came after the summary ended, toto wasn't rendering the link properly. It was processing the summary snippet, rather than taking a snippet of markdown'd article. I changed that, but I'm pretty sure I broke two tests, mostly because I didn't have the energy to figure out how to make the test library tell me what /actual value/ the test was computing. Sorry about that.

### CODE REVIEW

**Comment by lunks** [comment]
Your pull request has way more than what you put in its description.

**Comment by jbrains** [comment]
Yes. I'm a Novice at pull requests and don't know how to limit the pull to the specific set of commits. I suppose I could go back to the base release and cherry pick the commits on a new branch, then put a pull request for that, but I couldn't figure out how to do that with github itself. For example, I want this pull request to be only commits cdafda4..e46002f. If someone can point me to an explanation how to do that, I'll resubmit. Thanks.

**Comment by lunks** [comment]
Sure! Sorry If I seemed a little harsh there. Make sure you rebase your fork with latest version of toto. Check the latest commit of the official repo, check it out, then create a new branch. Cherry-pick your commits to that branch and then recreate the pull request with only the commits from that branch. If you need any help on doing any of this, you can find me @ freenode under the same nickname. I usually hang on #git, #rubyonrails and #ruby.

**Comment by jbrains** [comment]
I appreciate the apology. This time, I didn't need it. I guess I find myself in a good mood right now. I took it as a neutral statement. :) I think I know what to do, but I appreciate the offer of help.

**Comment by jbrains** [comment]
Replaced with pull request 88.

**Pull request closed without merging**
